configured_endpoints: 12
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/gmt%2Fgmt-01a797ab49f44c4f344b76b904f0eed8f646079572d4cf47badbc5b5917cc7d9.yml
openapi_spec_hash: e4b57dbfab233a444af937e6aba14d9e
config_hash: ec6e54d166b44c0fbddfaadbcdd4c8cf
